### ISSUE TITLE
Get leaflet sync working

### ISSUE THREAD

**Issue by coreysnipes** [Saijin-Naib/UAVArena#17]

**Comment by danbjoseph** [comment]
what is the desired/expected functionality?

**Comment by danbjoseph** [comment]
request is to implement both with a UI button to toggle the behavior

**Comment by danbjoseph** [comment]
oops, i thought i was in my own fork not yours and pushed a commit to the main branch
i think 90bf96ca38fbf4000bc7f08bc8444826eb04eba6 should implement this

**Comment by danbjoseph** [comment]
@Saijin-Naib did you have a chance to look at the new code?

**Comment by Saijin-Naib** [comment]
It runs, but I can't view any datasets with the commit as it is.

Does anything need to change?

Do we close my other branch if this supercedes all of that?

**Comment by Saijin-Naib** [comment]
This seems to be working perfectly under the latest commit, ae39642b62addfcc2d7ab45920c8967ab6318bfb, so I'll close this for now.
