### ISSUE TITLE
Popper has breaking API changes between v1 and V2

### ISSUE THREAD

**Issue by Saijin-Naib** [Saijin-Naib/UAVArena#20]

**Comment by Saijin-Naib** [comment]
Popper does indeed appear to be broken, our pop-over info screen does not draw when Info is pressed.

**Comment by danbjoseph** [comment]
talked to @Saijin-Naib and i will take a look at this as a first test of my ability to contribute.

**Comment by danbjoseph** [comment]
this was an issue with some of the html for Bootstrap’s modal component

**Comment by Saijin-Naib** [comment]
Easy fix, then?

**Comment by danbjoseph** [comment]
yes, it is fixed as part of #32 and i figured i could bundle some other commits/fixes into the PR before you merge it with the changes in your branch
