### ISSUE TITLE
consider moving folders of tiles to a different repo

### ISSUE THREAD

**Issue by danbjoseph** [Saijin-Naib/UAVArena#31]
cloning takes a significant amount of time - consider moving the data folder to its own repo so that developing the website doesn't require copying down all those assets?
<img width="679" alt="Screen Shot 2023-03-27 at 6 29 46 PM" src="https://user-images.githubusercontent.com/4806884/228089689-d8ec6d18-446b-4afb-9877-7294f3781db3.png">
although admittedly my internet is a little slow right now...
<img width="412" alt="Screen Shot 2023-03-27 at 6 33 57 PM" src="https://user-images.githubusercontent.com/4806884/228090053-f364dea9-6e92-47ea-a5d7-ef58f796e201.png">

**Comment by Saijin-Naib** [comment]
How would that work with our current setup? How would the main.js need to be modified to accommodate this?

**Comment by danbjoseph** [comment]
i don't think it would impact performance. for example, for the Missing Maps blog, the images are stored in a separate repository:
- https://github.com/MissingMaps/blog (folder of markdown posts)
- https://github.com/MissingMaps/img (images)

and websites pull map layers from other places all the time. 

i think the only change would be a minor edit to the path on [main.js#L158](https://github.com/Saijin-Naib/UAVArena/blob/master/main.js#L158)

**Comment by Saijin-Naib** [comment]
Alright, if you know how to implement this, I'll see about getting approval to make the data repository.

**Comment by danbjoseph** [comment]
need https://github.com/OpenDroneMap/UAVArena-data published as GitHub pages to finish this
should look something like this in settings
![Image](https://user-images.githubusercontent.com/4806884/236077358-0b188291-36d5-4310-8b50-fe53cd13db6b.png)

**Comment by Saijin-Naib** [comment]
I believe I published it a while back:  
![image](https://user-images.githubusercontent.com/19295950/236265222-1fee1729-b26a-4d98-93d8-856001244364.png)

Is it not reachable?

**Comment by danbjoseph** [comment]
my mistake. yes it is.

**Comment by Saijin-Naib** [comment]
All good!

Are we at a place where you consider this work item closed?

**Comment by Saijin-Naib** [comment]
Still not behaving even after #34 
```
01:09:15.045 Uncaught Error: Map container not found.
    _initContainer http://localhost:8080/libs/leaflet/leaflet.min.js:1
    initialize http://localhost:8080/libs/leaflet/leaflet.min.js:1
    e http://localhost:8080/libs/leaflet/leaflet.min.js:1
    map http://localhost:8080/libs/leaflet/leaflet.min.js:1
    <anonymous> http://localhost:8080/main.js:69
    jQuery 13
leaflet.min.js:1:38409
    _initContainer http://localhost:8080/libs/leaflet/leaflet.min.js:1
    initialize http://localhost:8080/libs/leaflet/leaflet.min.js:1
    e http://localhost:8080/libs/leaflet/leaflet.min.js:1
    map http://localhost:8080/libs/leaflet/leaflet.min.js:1
    <anonymous> http://localhost:8080/main.js:69
    jQuery 13
```
![image](https://user-images.githubusercontent.com/19295950/236381711-2f8097b8-dd85-4c8d-bec1-1fc70daf032a.png)

**Comment by danbjoseph** [comment]
very odd. what browser are you using? i tested in Chrome and Firefox.
the error mentions line 69
https://github.com/Saijin-Naib/UAVArena/blob/fcb6e12b4c5c66bc9e80fc6b18f8d838d09ed6b8/main.js#L69-L70

maybe if i move that block of code below the one that initiates the maps...

**Comment by Saijin-Naib** [comment]
Firefox 112 under Alpine Linux.

Hmm, maybe?

**Comment by danbjoseph** [comment]
try with the change in  ae39642b62addfcc2d7ab45920c8967ab6318bfb?

**Comment by Saijin-Naib** [comment]
Worked perfectly!

**Comment by Saijin-Naib** [comment]
So it looks like this work item, to move data to a separate UAVArena-Data repo, is complete and works properly, so I'm going to close this.
